### ISSUE TITLE
Website no workie

### ISSUE THREAD

**Issue by epicserve** [k-slug/k-slug.github.io#2]
Both http://www.k-slug.org and http://k-slug.org return no data.

**Comment by briancain** [comment]
@epicserve I think it has something to do with the DNS...because the site itself is hosted on Github.

**Comment by epicserve** [comment]
@sgsax Maybe you know something about that? @briancain Any idea what it needs to be set to?

**Comment by briancain** [comment]
I think at one point we were using campus dns? I had to set the CNAME in the repository when that happened...maybe something changed?

**Comment by sgsax** [comment]
It is managed by central DNS. Any way to find out if the IP changed?
Hostname is registered for 199.27.73.133, but if that changed, I have no
way of knowing about it. If you can find the new IP, I can have ITS
update DNS.

Seth

On 07/31/2014 11:05 AM, Brian Cain wrote:

> I think at one point we were using campus dns? I had to set the CNAME in
> the repository when that happened...maybe something changed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-slug/k-slug.github.io/issues/2#issuecomment-50780187.

## 

Seth Galitzer
The beatings will continue until morale has improved.

**Comment by epicserve** [comment]
Is this any help, https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider

**Comment by epicserve** [comment]
Also, here is the main page for custom domains, https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages

**Comment by briancain** [comment]
So when I curl where the website _should_ be...I get a HTTP 301....and when I curl k-slug.org I get that port 80 is unreachable o_O

```
brian@bigmac:~ $ curl http://k-slug.github.io/
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
brian@bigmac:~ $ curl http://k-slug.org
curl: (7) Failed to connect to k-slug.org port 80: Network is unreachable
```

It looks like k-slug.github.io IP is `23.235.47.133` when I ping it.

**Comment by epicserve** [comment]
@briancain check out the links above.

**Comment by briancain** [comment]
@epicserve I've already done as much as I can do on the Github side (i.e. a CNAME file in the repo)...I don't control the DNS though so not much I can do there.

**Comment by epicserve** [comment]
@briancain, @sgsax I think [this](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider#configuring-an-a-record-with-your-dns-provider) is what ITS needs to do.

If you guys agree ... @sgsax can you send an email to ITS to make the change?

**Comment by sgsax** [comment]
Request to ITS has been sent. It should hopefully be done in the next 7
days...

Seth

On 07/31/2014 11:25 AM, epicserve wrote:

> @briancain https://github.com/briancain, @sgsax
> https://github.com/sgsax I think this
> https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider#configuring-an-a-record-with-your-dns-provider
> is what ITS needs to do.
> 
> If you guys agree ... @sgsax https://github.com/sgsax can you send an
> email to ITS to make the change?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-slug/k-slug.github.io/issues/2#issuecomment-50782964.

## 

Seth Galitzer
The beatings will continue until morale has improved.

**Comment by briancain** [comment]
:+1: 

Will close once it's back, thanks @sgsax !

**Comment by epicserve** [comment]
@sgsax Good Job!

![Good Job](http://i.imgur.com/0dtimfr.gif)

**Comment by briancain** [comment]
@sgsax @epicserve Looks like the website is up and working. Will close this now.

![awyis](http://i.imgur.com/xMtDh.jpg)

**Comment by epicserve** [comment]
Nice!
